version: '2'
services:
  nginx:
    image: nginx:latest
    container_name: ng01
    ports:
      - "8000:8000"
    volumes:
      - ./dswebsite:/app/dswebsite
      - ./nginx:/etc/nginx/conf.d
      - ./dswebsite/deepstyle/static:/app/static
    depends_on:
      - web

  web:
    build: .
    container_name: dg01
    command: bash /app/start_app_wrapper.sh
    depends_on:
      - db
    volumes:
      - ./dswebsite:/app/dswebsite
      - ./dswebsite/deepstyle/static:/app/static
    expose:
      - "8000"

  db:
    image: postgres:latest
    container_name: ps01
    restart: always
    environment:
      - POSTGRES_USER=test
      - POSTGRES_PASSWORD=test
      - POSTGRES_DB=test_db
    ports:
      - "5431:5432"
