# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-07 03:09
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_name', models.CharField(max_length=200)),
                ('style_image_path', models.CharField(max_length=1000)),
                ('output_image_path', models.CharField(max_length=1000)),
                ('input_image_path', models.CharField(max_length=1000)),
                ('output_width', models.PositiveSmallIntegerField()),
                ('iterations', models.PositiveIntegerField(default=2000)),
                ('content_weight', models.FloatField()),
                ('style_weight', models.FloatField()),
                ('learning_rate', models.FloatField()),
                ('style_layer_weight_exp', models.FloatField()),
                ('perserve_color', models.BooleanField()),
                ('pooling', models.CharField(choices=[('MAX', 'max'), ('AVG', 'avg')], default='MAX', max_length=3)),
                ('job_status', models.CharField(choices=[('Q', 'Queued'), ('P', 'In Progress'), ('C', 'Completed')], default='Q', max_length=1)),
                ('job_added', models.DateTimeField(default=datetime.datetime.now)),
                ('job_start', models.DateTimeField(blank=True)),
                ('job_completed', models.DateTimeField(blank=True)),
            ],
        ),
    ]
