# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-07 04:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deepstyle', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_name', models.CharField(max_length=500)),
                ('image_path', models.CharField(max_length=1000)),
            ],
        ),
    ]
