# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-07 05:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deepstyle', '0005_auto_20171107_0500'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='job_description',
            field=models.TextField(default='Just another deepstyle job'),
        ),
    ]
