# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-07 05:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('deepstyle', '0006_job_job_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='image_type',
            field=models.CharField(choices=[('I', 'Input'), ('O', 'Output')], default='I', max_length=1),
        ),
        migrations.AlterField(
            model_name='job',
            name='input_image_path',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='deepstyle.Image'),
        ),
        migrations.AlterField(
            model_name='job',
            name='output_image_path',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='deepstyle.Image'),
        ),
        migrations.AlterField(
            model_name='job',
            name='style_image_path',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='deepstyle.Image'),
        ),
    ]
