# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-07 05:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deepstyle', '0007_auto_20171107_0542'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image_path',
            field=models.FileField(upload_to=''),
        ),
    ]
