# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-07 21:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deepstyle', '0009_auto_20171107_2112'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='image_description',
            field=models.TextField(default='Just another image'),
        ),
    ]
