# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-08 01:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('deepstyle', '0010_image_image_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='input_image_path',
            new_name='input_image',
        ),
        migrations.RenameField(
            model_name='job',
            old_name='output_image_path',
            new_name='output_image',
        ),
        migrations.RenameField(
            model_name='job',
            old_name='style_image_path',
            new_name='style_image',
        ),
    ]
