# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-08 03:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deepstyle', '0011_auto_20171108_0111'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='content_weight_blend',
            field=models.FloatField(default=1),
        ),
        migrations.AlterField(
            model_name='job',
            name='content_weight',
            field=models.FloatField(default=5.0),
        ),
        migrations.AlterField(
            model_name='job',
            name='iterations',
            field=models.PositiveIntegerField(default=1000),
        ),
        migrations.AlterField(
            model_name='job',
            name='learning_rate',
            field=models.FloatField(default=10.0),
        ),
        migrations.AlterField(
            model_name='job',
            name='perserve_color',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='job',
            name='style_layer_weight_exp',
            field=models.FloatField(default=1),
        ),
        migrations.AlterField(
            model_name='job',
            name='style_weight',
            field=models.FloatField(default=500.0),
        ),
    ]
