# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-09 22:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('deepstyle', '0012_auto_20171108_0355'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='image_path',
            new_name='image_file',
        ),
    ]
