# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-10 19:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deepstyle', '0016_auto_20171110_0410'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='style_scale',
            field=models.FloatField(default=1.0),
        ),
        migrations.AlterField(
            model_name='job',
            name='job_status',
            field=models.CharField(choices=[('Q', 'Queued'), ('P', 'In Progress'), ('C', 'Completed'), ('F', 'Failed'), ('PF', 'Progress Failed')], default='Q', max_length=2),
        ),
    ]
