# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-10 19:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('deepstyle', '0017_auto_20171110_1941'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='perserve_color',
            new_name='preserve_color',
        ),
    ]
