# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-13 07:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deepstyle', '0019_auto_20171113_0718'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='input_image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='job',
            name='style_image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
