# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-13 15:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('deepstyle', '0020_auto_20171113_0736'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='input_image',
            field=models.ForeignKey(null='False', on_delete=django.db.models.deletion.CASCADE, related_name='+', to='deepstyle.Image'),
        ),
        migrations.AlterField(
            model_name='job',
            name='output_image',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='style_image',
            field=models.ForeignKey(null='False', on_delete=django.db.models.deletion.CASCADE, related_name='+', to='deepstyle.Image'),
        ),
    ]
