# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-13 15:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deepstyle', '0022_auto_20171113_1543'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='input_image',
            field=models.ImageField(blank=True, null=True, upload_to='media/'),
        ),
    ]
