# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-15 18:21
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deepstyle', '0025_auto_20171113_1714'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='content_weight',
            field=models.FloatField(default=5.0, verbose_name='Content Weight [100 - 1000]'),
        ),
        migrations.AlterField(
            model_name='job',
            name='content_weight_blend',
            field=models.FloatField(default=1, verbose_name='Content Weight Blend [0.0 - 1.0]'),
        ),
        migrations.AlterField(
            model_name='job',
            name='iterations',
            field=models.PositiveIntegerField(default=1000, verbose_name='Iterations [500 - 2000] (Higher iterations might output better results, however, at higher processing time)'),
        ),
        migrations.AlterField(
            model_name='job',
            name='learning_rate',
            field=models.FloatField(default=10.0, verbose_name='Learning Rate [100 - 1000]'),
        ),
        migrations.AlterField(
            model_name='job',
            name='output_width',
            field=models.PositiveSmallIntegerField(default=600, validators=[django.core.validators.MaxValueValidator(1000), django.core.validators.MinValueValidator(100)], verbose_name='Output Width [100 - 1000] (Higher width will output higher resolution image, however, at higher processing time)'),
        ),
        migrations.AlterField(
            model_name='job',
            name='style_layer_weight_exp',
            field=models.FloatField(default=1, verbose_name='Style Layer Weight Exp [100 - 1000]'),
        ),
        migrations.AlterField(
            model_name='job',
            name='style_scale',
            field=models.FloatField(default=1.0, verbose_name='Style Scale [100 - 1000]'),
        ),
        migrations.AlterField(
            model_name='job',
            name='style_weight',
            field=models.FloatField(default=500.0, verbose_name='Style Weight [100 - 1000]'),
        ),
    ]
