# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-15 19:01
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deepstyle', '0026_auto_20171115_1821'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='iterations',
            field=models.PositiveIntegerField(default=1000, validators=[django.core.validators.MaxValueValidator(2000, message='Value too high'), django.core.validators.MinValueValidator(500, message='Value too low')], verbose_name='Iterations [500 - 2000] (Higher iterations might output better results, however, at higher processing time)'),
        ),
        migrations.AlterField(
            model_name='job',
            name='output_width',
            field=models.PositiveSmallIntegerField(default=600, validators=[django.core.validators.MaxValueValidator(1000, message='Value too high'), django.core.validators.MinValueValidator(100, message='Value too low')], verbose_name='Output Width [100 - 1000] (Higher width will output higher resolution image, however, at higher processing time)'),
        ),
    ]
