# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-15 18:27
from __future__ import unicode_literals

import deepstyle.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deepstyle', '0026_auto_20171115_1821'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='output_width',
            field=models.PositiveSmallIntegerField(default=600, validators=[deepstyle.models.validate_even], verbose_name='Output Width [100 - 1000] (Higher width will output higher resolution image, however, at higher processing time)'),
        ),
    ]
