# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-16 07:35
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deepstyle', '0029_auto_20171116_0730'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='style_blend_weight',
        ),
        migrations.AddField(
            model_name='job',
            name='style_blend_weights',
            field=models.FloatField(default=1, validators=[django.core.validators.MaxValueValidator(1.0, message='Value too high'), django.core.validators.MinValueValidator(0.0, message='Value too low')], verbose_name='Style Blend Weights [0.0 - 1.0]'),
        ),
    ]
