# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-17 07:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deepstyle', '0030_auto_20171116_0735'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='input_image',
            field=models.ImageField(max_length=500, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='job',
            name='output_image',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='style_image',
            field=models.ImageField(max_length=500, null=True, upload_to=''),
        ),
    ]
