# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-17 09:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deepstyle', '0033_auto_20171117_0832'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='input_image',
            field=models.ImageField(max_length=500, null=True, upload_to='', verbose_name='Input Image (Uplaoding large images may take a while.)'),
        ),
        migrations.AlterField(
            model_name='job',
            name='style_image',
            field=models.ImageField(max_length=500, null=True, upload_to='', verbose_name='Style Image (Uploading large images may take a while.)'),
        ),
    ]
